import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import Cta from "./components/CTA/cta";
import Footer from "./components/Footer/Footer";
import LayoutClient from "./components/LayoutClient";


const instrumentSerif = Instrument_Serif({
  variable: "--font-F01",
  subsets: ["latin"],
  weight: ["400"]
});

const inter = Inter({
  variable: "--font-F02",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Quint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={`${inter.variable} ${instrumentSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <LayoutClient />

        {children}

        <div className="w-[100%] h-auto relative flex flex-col items-stretch justify-start">

          <div className="w-[100%] sticky top-0 left-auto right-auto bottom-0 z-[2]">
            <Cta />
          </div>

          <div className="block pt-[184px] w-[100%] overflow-hidden relative z-[3]">
            <div className="w-[100%] h-[100%]">
              <Footer />
            </div>
          </div>

        </div>
      </body>
    </html>
  );
}
