import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import Cta from "./components/CTA/cta";
import Footer from "./components/Footer/Footer";
import LayoutClient from "./components/LayoutClient";


const instrumentSerif = Instrument_Serif({
  variable: "--font-F01",
  subsets: ["latin"],
  weight: ["400"]
});

const inter = Inter({
  variable: "--font-F02",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Quint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={`${inter.variable} ${instrumentSerif.variable} h-full antialiased`}>
      <body className="flex flex-col">
        <div className="w-full overflow-x-clip">
          <LayoutClient />
          {children}
        </div>

        <div className="w-full h-auto relative flex flex-col items-stretch justify-start">
          <div className="w-full sticky top-0 z-[2]">
            <Cta />
          </div>
          <div className="block pt-[184px] w-full overflow-hidden relative z-[3]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
