import { Instrument_Serif, Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Cta from "./components/CTA/cta";
import Footer from "./components/Footer/Footer";

const instrumentSerif = Instrument_Serif({
  variable: "--font-F01",
  subsets: ["latin"],
  weight:["400"]
});

const inter = Inter({
  variable: "--font-F02",
  subsets: ["latin"],
  weight:["400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${instrumentSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {children}

        <Cta />
        <Footer />
      </body>
    </html>
  );
}
